### ISSUE TITLE
Which license would you like to apply to this project?

### ISSUE THREAD

**Issue by unixerius** [FWSquatch/do180-practice#1]
Good day,

I have forked your project and I am in the process of updating it for both RHEL 8 and the new EX188 exam. 

-> https://github.com/unixerius/EX188-practice

For the time being, I have applied the CC-BY-SA 4.0 license to my fork of the project. But I want to make sure that this does not conflict with your own wishes regarding licensing. Your project did not include a LICENSE.txt, so I'm asking you via a Github issue.

**Comment by FWSquatch** [comment]
I haven't thought about this project in a long time. I never quite got it to where I wanted it. I'm glad to see someone picking it up and running with it. I have no problem with the CC-BY-SA 4.0 license. Good luck with your fork!

**Comment by unixerius** [comment]
I am glad to hear this! Thank you for your support!
